# Generated by Django 5.1.4 on 2025-01-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Команда'},
        ),
    ]
